"""add approved_by column to movies

Revision ID: 89f9283c383b
Revises: bbaeb3689393
Create Date: 2026-09-07 11:38:28.141678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f9283c383b'
down_revision: Union[str, Sequence[str], None] = 'bbaeb3689393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_movies_approved_by'), 'movies', ['approved_by'], unique=False)
    op.drop_constraint(op.f('movies_created_by_fkey'), 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'users', ['approved_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movies', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key(op.f('movies_created_by_fkey'), 'movies', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_movies_approved_by'), table_name='movies')
    op.drop_column('movies', 'approved_by')
    # ### end Alembic commands ###
