"""Add video url

Revision ID: a311276f7e12
Revises: 89f9283c383b
Create Date: 2026-09-11 11:15:07.447364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a311276f7e12'
down_revision: Union[str, Sequence[str], None] = '89f9283c383b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('video_file_id', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('video_size_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'video_size_bytes')
    op.drop_column('movies', 'video_file_id')
    # ### end Alembic commands ###
